### ISSUE TITLE
Debase failing to install on vscode Jekyll container

### ISSUE THREAD

**Issue by lsli8888** [ruby-debug/debase#103]
When building my container on VSCode, I get a "failed to build gem native extension" error.  Here's a snippet of the output:

```
#0 149.9 ERROR:  Error installing ruby-debug-ide:
[2023-03-02T06:31:35.062Z] #0 149.9 	ERROR: Failed to build gem native extension.
#0 149.9 
#0 149.9     current directory: /usr/local/rvm/gems/default/gems/ruby-debug-ide-0.7.3/ext
#0 149.9 /usr/local/rvm/rubies/ruby-2.7.5/bin/ruby mkrf_conf.rb
#0 149.9 Installing base gem
#0 149.9 Building native extensions. This could take a while...
#0 149.9 Building native extensions. This could take a while...
#0 149.9 ERROR: Failed to build gem native extension.
```

I've attached the output log (output.txt), devcontainer config files as well - i.e. Dockerfile, devcontainer.json, post-create.sh in an attached zip file.

I would appreciate any help!  I tried updating to Ruby 2.7.7 without any success.  I also tried specifying an older debase and ruby-debug-ide version without success.  This build has previously worked for me.  Not sure why it's not working now.

[DebaseIssue.zip](https://github.com/ruby-debug/debase/files/10868721/DebaseIssue.zip)

**Comment by hurricup** [comment]
ruby is bad inside the container. It is rvm binary ruby built incrorrectly.
```
make: /usr/bin/mkdir: No such file or directory
```
Should be installed with `--disable-binary`

This distro won't be able to install any binary extension, not only debugger.
