### ISSUE TITLE
Ruby 2.3.0 compatibility

### ISSUE THREAD

**Issue by JanStevens** [ruby-debug/debase#24]
Can you release a new version of debase that tracks a more recent version of `debase-ruby_core_source`?

Right now my bundler used version 0.8.1 (which does not have ruby 2.3) and the installation fails. I had to manually do the following

```
gem install debase-ruby_core_source -v 0.8.4
gem install debase -v '0.2.2.beta5'
```

before my bundle install worked again.

Thanks!

**Comment by hurricup** [comment]
I believe this is obsolete.
