### ISSUE TITLE
ERROR:  Error installing debase: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by surkuar** [ruby-debug/debase#57]
Ruby - v ==> ruby 2.4.3p205 (2017-12-14 revision 61247) [i386-mingw32]

C:\Ruby24\bin>gem install debase
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing debase:
        ERROR: Failed to build gem native extension.
**gem_make.out**
current directory: C:/Ruby24/lib/ruby/gems/2.4.0/gems/debase-0.2.2/ext
C:/Ruby24/bin/ruby.exe -r ./siteconf20180302-10448-1gll6k.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby24/bin/$(RUBY_BASE_NAME)
	--with-ruby-dir
	--without-ruby-dir
	--with-ruby-include
	--without-ruby-include=${ruby-dir}/include
	--with-ruby-lib
	--without-ruby-lib=${ruby-dir}/lib
C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
	from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
	from extconf.rb:31:in `block in <main>'
	from C:/Ruby24/lib/ruby/gems/2.4.0/gems/debase-ruby_core_source-0.10.2/lib/debase/ruby_core_source.rb:14:in `create_makefile_with_core'
	from extconf.rb:48:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby24/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/debase-0.2.2/mkmf.log

extconf failed, exit code 1

**mkmf.log**
"i686-w64-mingw32-gcc -o conftest.exe -IC:/Ruby24/include/ruby-2.4.0/i386-mingw32 -IC:/Ruby24/include/ruby-2.4.0/ruby/backward -IC:/Ruby24/include/ruby-2.4.0 -I. -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=i686 -mtune=generic -O2 -pipe conftest.c  -L. -LC:/Ruby24/lib -L. -pipe     -lmsvcrt-ruby240  -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

**Comment by ViugiNick** [comment]
@surkuar 1) Do you have Devkit installed (https://github.com/ruby-debug/ruby-debug-ide/issues/140#issuecomment-376746682)
Looks like you have an error about it: `C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:457:in try_do': The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first. from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:588:in try_cpp'`

2) Maybe installing the latest `debase` version(0.2.3.beta5) will be easier
