### ISSUE TITLE
ERROR:  Error installing debase:

### ISSUE THREAD

**Issue by M-Hagras** [ruby-debug/debase#65]
`when I run: gem install debase --pre
Building native extensions. This could take a while...
ERROR:  Error installing debase:
        ERROR: Failed to build gem native extension.

    current directory: /Users/user/.rvm/gems/ruby-2.3.7/gems/debase-0.2.3.beta2/ext
/Users/user/.rvm/rubies/ruby-2.3.7/bin/ruby -r ./siteconf20180902-70061-1p5vfd7.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/user/.rvm/rubies/ruby-2.3.7/bin/$(RUBY_BASE_NAME)
/Users/user/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- debase/ruby_core_source (LoadError)
        from /Users/user/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from extconf.rb:28:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/user/.rvm/gems/ruby-2.3.7/gems/debase-0.2.3.beta2 for inspection.
Results logged to /Users/user/.rvm/gems/ruby-2.3.7/extensions/x86_64-darwin-17/2.3.0/debase-0.2.3.beta2/gem_make.out
`

the content of '/Users/user/.rvm/gems/ruby-2.3.7/extensions/x86_64-darwin-17/2.3.0/debase-0.2.3.beta2/gem_make.out' is:
`current directory: /Users/user/.rvm/gems/ruby-2.3.7/gems/debase-0.2.3.beta2/ext
/Users/user/.rvm/rubies/ruby-2.3.7/bin/ruby -r ./siteconf20180902-70061-1p5vfd7.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/user/.rvm/rubies/ruby-2.3.7/bin/$(RUBY_BASE_NAME)
/Users/user/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- debase/ruby_core_source (LoadError)
	from /Users/user/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from extconf.rb:28:in `<main>'

extconf failed, exit code 1
`

I am using ruby 2.3.7 installed via rvm on mac high sierra v10.13.6

I have tried to clear rvm with all rubies and gem, and try reinstall with no thing changing, the gem is required to install gem 'ruby-debug-ide' used by RubyMine Debugger

**Comment by ViugiNick** [comment]
@M-Hagras do you have debase/ruby-core-sources installed in your ruby-2.3.7?

**Comment by M-Hagras** [comment]
@ViugiNick Thanks for your reply,
yes debase-ruby_core_source (0.10.3) is installed

**Comment by ViugiNick** [comment]
https://github.com/os97673/debase-ruby_core_source/tree/master/lib/debase/ruby_core_source looks like there is no such version in this gem, can you please try another ruby version

**Comment by M-Hagras** [comment]
For ruby-2.5.1 I have no problem
debase (0.2.3.beta2, 0.2.2)
debase-ruby_core_source (0.10.3)

**Comment by ViugiNick** [comment]
@M-Hagras Ok, I'll try to add 2.3.7 ASAP

**Comment by ViugiNick** [comment]
@M-Hagras It should work now with the latest `debase` version

**Comment by liujinxia** [comment]
use rvm and install ruby newest version, then use rubymine debug mode , fix my problem

**Comment by ViugiNick** [comment]
@liujinxia Do you mean that everything works fine now?

**Comment by jvarness** [comment]
> use rvm and install ruby newest version, then use rubymine debug mode , fix my problem

This was what I had to do. It was because the version of ruby that I had installed didn't come with ruby sources.

**Comment by amarpalbajwa** [comment]
Try
```
gem install debase -- --with-cflags="-Wno-error=implicit-function-declaration"
```
